import React, { type CSSProperties } from 'react';
import './GradualBlur.css';
type GradualBlurProps = {
    position?: 'top' | 'bottom' | 'left' | 'right';
    strength?: number;
    height?: string;
    width?: string;
    divCount?: number;
    exponential?: boolean;
    zIndex?: number;
    animated?: boolean | 'scroll';
    duration?: string;
    easing?: string;
    opacity?: number;
    curve?: 'linear' | 'bezier' | 'ease-in' | 'ease-out' | 'ease-in-out';
    responsive?: boolean;
    mobileHeight?: string;
    tabletHeight?: string;
    desktopHeight?: string;
    mobileWidth?: string;
    tabletWidth?: string;
    desktopWidth?: string;
    preset?: 'top' | 'bottom' | 'left' | 'right' | 'subtle' | 'intense' | 'smooth' | 'sharp' | 'header' | 'footer' | 'sidebar' | 'page-header' | 'page-footer';
    gpuOptimized?: boolean;
    hoverIntensity?: number;
    target?: 'parent' | 'page';
    onAnimationComplete?: () => void;
    className?: string;
    style?: CSSProperties;
};
declare const GradualBlurMemo: React.NamedExoticComponent<React.PropsWithChildren<GradualBlurProps>>;
export default GradualBlurMemo;
